database:
  type: sqlite
  path: 'db'
  filename: 'finance.db'
language:
  default: en
logging:
  level: DEBUG  # Может быть DEBUG, INFO, WARNING, ERROR, CRITICAL
  path: 'logs'
  filename: 'log'
db_logging:
  level: DEBUG  # Может быть DEBUG, INFO, WARNING, ERROR, CRITICAL
  path: 'logs'
  filename: 'db_log'