version: '3'

services:
  bot:
    image: "finance_bot"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./db:/app/db  # Монтирование папки db из вашего проекта в папку /app/db в контейнере
    environment:
      - DB_PATH=/app/db/finance.db
    restart: always
